# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MMCL <- function(y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, id, N, a, p, power) {
    .Call(`_frailtyMMpen_MMCL`, y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, id, N, a, p, power)
}

MMME <- function(y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, N, n, p, power) {
    .Call(`_frailtyMMpen_MMME`, y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, N, n, p, power)
}

MMRE <- function(y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, id, N, a, p, power) {
    .Call(`_frailtyMMpen_MMRE`, y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, id, N, a, p, power)
}

MMRELS <- function(y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, id, N, a, p, power) {
    .Call(`_frailtyMMpen_MMRELS`, y, X, d, coef0, lambda0, tht0, frailty, penalty, gam, tune, id, N, a, p, power)
}

LogLikCL <- function(y, X, d, coef0, lambda0, tht0, frailty, id, N, a, p, power) {
    .Call(`_frailtyMMpen_LogLikCL`, y, X, d, coef0, lambda0, tht0, frailty, id, N, a, p, power)
}

LogLikME <- function(y, X, d, coef0, lambda0, tht0, frailty, N, n, p, power) {
    .Call(`_frailtyMMpen_LogLikME`, y, X, d, coef0, lambda0, tht0, frailty, N, n, p, power)
}

LogLikRE <- function(y, X, d, coef0, lambda0, tht0, frailty, id, N, a, p, power) {
    .Call(`_frailtyMMpen_LogLikRE`, y, X, d, coef0, lambda0, tht0, frailty, id, N, a, p, power)
}

