# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MMCL <- function(y, X, d, coef0, lambda0, tht0, frailty, penalty, tune, a, b, p) {
    .Call(`_frailtyMMpen_MMCL`, y, X, d, coef0, lambda0, tht0, frailty, penalty, tune, a, b, p)
}

LogLikCL <- function(y, X, d, coef0, lambda0, tht0, frailty, a, b, p) {
    .Call(`_frailtyMMpen_LogLikCL`, y, X, d, coef0, lambda0, tht0, frailty, a, b, p)
}

