# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FaccCal <- function(y, x, Target, A, C) {
    .Call(`_MMsplit_FaccCal`, y, x, Target, A, C)
}

